-- AlterTable
ALTER TABLE `users` ADD COLUMN `lastLevelUpdate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `level` ENUM('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'CHALLENGER') NOT NULL DEFAULT 'BRONZE',
    ADD COLUMN `monthlyRevenue` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `totalRevenue` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `transactionCount` INTEGER NOT NULL DEFAULT 0;
